In [1]:
import duckdb
import pandas as pd
import plotly.express as px
from plotly_calplot import calplot

from common.env_variables import DUCKDB_DWH_FILE


def execute(sql_statement):
    conn = duckdb.connect(DUCKDB_DWH_FILE, read_only=True)
    _df = conn.execute(sql_statement).df()
    conn.close()
    return _df


def display_df(_df):
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, "expand_frame_repr", False,
                           "display.float_format", '${:,.2f}'.format):
        display(_df.fillna('.'))

In [2]:
execute(f'''
SELECT table_schema,
       table_name,
       table_type
  FROM information_schema.tables
''')

  table_schema                 table_name  table_type
0         main            fact_online_job  BASE TABLE
1      curated               job_location        VIEW
2      curated                        job        VIEW
3      curated                 online_job        VIEW
4         main  online_job_by_date_change        VIEW
5         main                   location        VIEW
6         main  job_online_by_date_change        VIEW
7         main   count_online_job_by_date        VIEW
8         main                top_company        VIEW
9         main               top_location        VIEW

In [3]:
execute(f'''
SELECT *
  FROM curated.online_job
 ORDER BY load_timestamp DESC,
          job_id DESC
 LIMIT 0
''')

Empty DataFrame
Columns: [job_id, load_timestamp, online_at, url, day, month, year]
Index: []

In [4]:
execute(f'''
SELECT *
  FROM curated.job
 ORDER BY load_timestamp DESC,
          job_id DESC
 LIMIT 20
''')

,job_id,load_timestamp,title,online_status,is_anonymous,should_display_early_applicant,contract_type,work_type,online_date,company_name,description_introduction,description_responsabilities,description_requirements,description_perks,day,month,year
0,8756987,2022-09-27 22:00:00,Volljurist / Syndikusrechtsanwalt (Rechtsanwal...,online,False,False,NaN,NaN,2022-09-27T20:28:32Z,HypoVereinsbank – Member of UniCredit,"Die HypoVereinsbank ist Teil der UniCredit, ei...",Es erwartet Sie eine herausfordernde Tätigkeit...,Volljurist:in mit idealerweise zwei Prädikatse...,#EnjoyMunich: Arbeiten Sie in der schönsten St...,27,9,2022
1,8756986,2022-09-27 22:00:00,Empfangsmitarbeiter (m/w/d),online,False,False,NaN,NaN,2022-09-27T20:26:59Z,Motel One München Messe,Unsere Mitarbeiter stehen im Mittelpunkt. Ob a...,Im Fokus steht die professionelle Betreuung un...,Ob als Hotelprofi oder im Quereinstieg – Sie p...,International Karriere machen\nGünstig übernac...,27,9,2022
2,8756985,2022-09-27 22:00:00,Nachtportier – „Die Nachteule“*,online,False,False,NaN,NaN,2022-09-27T20:26:53Z,Novum Management GmbH the niu Leo,NOVUM Hospitality betreibt als familiengeführt...,Als „Nachteule“ bist Du während der Nacht erst...,"Du bist ein leidenschaftlicher Gastgeber, der ...",familiengeführt • Family & Friends Raten • NOV...,27,9,2022
3,8756984,2022-09-27 22:00:00,Manager Customer Service Center (m/w/d) | Remo...,online,False,False,NaN,NaN,2022-09-27T20:26:48Z,Deutsche Hospitality Konzernzentrale,Die fünf Hotelmarken der Deutschen Hospitality...,Markenübergreifende Optimierung/ Vereinfachung...,Sie haben eine Ausbildung bzw. ein Studium im ...,NaN,27,9,2022
4,8756983,2022-09-27 22:00:00,Barkeeper / Bartender für die Atrium Bar (m/w/d),online,False,False,NaN,NaN,2022-09-27T20:26:43Z,"Radisson Blu Hotel, Berlin",Zentral zwischen Alexanderplatz und Museumsins...,"Wir, die Radisson Hotel Group, sind ein Teil v...",Yes I Can! spirit,NaN,27,9,2022
5,8756982,2022-09-27 22:00:00,Commis de rang / Servicemitarbeiter (m/w/x),online,False,False,NaN,NaN,2022-09-27T20:26:37Z,Steigenberger Inselhotel,Sie sind fasziniert von Hotellerie und Gastfre...,Möglichkeit verschiedener Einsatzbereiche:Serv...,abgeschlossene Ausbildung in der Hotellerie od...,Attraktive Mitarbeiterrate für unsere Hotels\n...,27,9,2022
6,8756981,2022-09-27 22:00:00,"Servicemitarbeiter ""Frühstück"" (m/w/d)",online,False,False,NaN,NaN,2022-09-27T20:26:32Z,Vienna House Easy Leipzig,"Das Vienna House Easy Leipzig, inmitten der In...",Du bist für das Wohlbefinden unserer Gäste ver...,Du verfügst (wünschenswerterweise) über erste ...,Verantwortungsvolle Tätigkeiten mit eigenständ...,27,9,2022
7,8756980,2022-09-27 22:00:00,Frühstücksleitung (m/w/x),online,False,False,NaN,NaN,2022-09-27T20:26:27Z,Steigenberger Parkhotel,Sie sind fasziniert von Hotellerie und Gastfre...,Als herzlicher Gastgeber begrüßen und platzier...,Idealerweise abgeschlossene Ausbildung in der...,Attraktive Mitarbeiterrate für unsere Hotels\n...,27,9,2022
8,8756979,2022-09-27 22:00:00,Servicemitarbeiter (m/w/x),online,False,False,NaN,NaN,2022-09-27T20:26:22Z,IntercityHotel Ulm,"Sie wissen, wie vielseitig das Businessleben s...",Abwechslungsreiche Aufgaben in einem Team mit ...,Ausbildung oder relevante Berufserfahrung in d...,Attraktive Mitarbeiterrate für unsere Hotels\n...,27,9,2022
9,8756978,2022-09-27 22:00:00,Guest Service Agent (all genders),online,False,False,NaN,NaN,2022-09-27T20:26:16Z,Premier Inn Frankfurt City Centre,"Wir sind Premier Inn! Großartige Teams, herzli...",Als Guest Service Agent bzw. Team Member Groun...,Du bist serviceorientiert und hast eine einneh...,Tolle Rahmenbedingungen: Du erhältst einen unb...,27,9,2022
10,8756977,2022-09-27 22:00:00,Supervisor Haustechnik / Supervisor Technik (m...,online,False,False,NaN,NaN,2022-09-27T20:26:11Z,"Radisson Blu Hotel, Frankfurt",#EVERY MOMENT MATTERS @ https://careers.radiss...,"Wir, die Radisson Hotel Group, sind eine der g...","""Yes I Can!""-Spirit",NaN,27,9,2022
11,8756976,2022-09-27 22:00:00,Chef De Rang(m/w/x),online,False,False,NaN,NaN,2022-09-27T20:26:05Z,Steigenberger Inselhotel,Sie sind fasziniert von Hotellerie und Gastfre...,Betreuung der Kunden vom Erstkontakt bis zur R...,abgeschlossene Ausbildung zum Restaurantfachma...,Attraktive Mitarbeiterrate für unsere Hotels\n...,27,9,2022
12,8756975,2022-09-27 22:00:00,Leiter Empfang / Front Office Manager in Vollz...,online,False,False,NaN,NaN,2022-09-27T20:25:45Z,Maritim Hotel Ingolstadt,"Interessante Aufgaben, gute Bezahlung und toll...",Verantwortung für einen reibungslosen Ablauf i...,Abgeschlossene Ausbildung im Hotelbereich\nMeh...,Weihnachtsgeld\nBetriebliche Altersvorsorge\nV...,27,9,2022
13,8756974,2022-09-27 22:00:00,Ausbildung Koch (m/w/d),online,False,False,NaN,NaN,2022-09-27T20:25:12Z,Maritim Hotel Ingolstadt,"Interessante Aufgaben, gute Bezahlung und toll...",Ausbildung auf unterschiedlichen Posten: Banke...,Praktikum in der Gastronomie oder Erfahrung du...,Auszubildenden Events\nMitarbeiter - und Famil...,27,9,2022
14,8756973,2022-09-27 22:00:00,Kellner / Servicekraft (m/w/d),online,False,False,NaN,NaN,2022-09-27T20:23:25Z,MARITIM Hotel Bellevue Kiel,"Interessante Aufgaben, gute Bezahlung und toll...","Empfang, Bedienung und Betreuung der Gäste\nSe...","Ausbildung in der Hotellerie oder Gastronomie,...",Vermögenswirksame Leistungen\nbis zu 100% Weih...,27,9,2022
15,8756972,2022-09-27 22:00:00,Front Office Agent (m/w/d) + 10% fixe Zulage O...,online,False,False,NaN,NaN,2022-09-27T20:21:39Z,Crowne Plaza Düsseldorf – Neuss,"Mit über 120 Hotels in Deutschland, Belgien un...","Wir wissen was es bedeutet, nicht jede Woche d...",wünschenswert ist eine Ausbildung im Hotelfach...,10% Flexibiliätszulage monatlich ON TOP zu Ihr...,27,9,2022
16,8756971,2022-09-27 22:00:00,Reservierungsmitarbeiter (m/w/d) ab 01.11.2022...,online,False,False,NaN,NaN,2022-09-27T20:21:33Z,Mercure Hotel Hannover City,Das Mercure Hotel Hannover City mit seinen 145...,Annahme und Abwicklung von telefonischen und s...,Du hast eine abgeschlossene Ausbildung in der ...,sämtliche Vorteile einer internationalen Hotel...,27,9,2022
17,8756970,2022-09-27 22:00:00,Frühstückskraft Service (m/w/d) ab 01.10.2022 ...,online,False,False,NaN,NaN,2022-09-27T20:21:28Z,Mercure Hotel Hannover City,Du liebst es im Service zu arbeiten und Mensch...,Betreuung unserer internationalen Gäste währen...,Du bist Gast- und Serviceorientiert ? \n Du bi...,sämtliche Vorteile einer internationalen Hotel...,27,9,2022
18,8756969,2022-09-27 22:00:00,Executive Chef (m/w/d),online,False,False,NaN,NaN,2022-09-27T20:21:22Z,Konen & Lorenzen Recruitment Consultants,Für ein exklusives 5-Sterne Hotel im Rheinland...,Verantwortung über das gesamte operative und a...,Abgeschlossene Berufsausbildung als Koch\nMehr...,Attraktives Gehaltspaket\nUnbefristeter Arbeit...,27,9,2022
19,8756968,2022-09-27 22:00:00,Chef de Partie (m/w/d) für unser Sternerestaur...,online,False,False,NaN,NaN,2022-09-27T20:21:17Z,40 SECONDS BERLIN,40 SECONDS BERLIN ist ein Full-Service-Dienstl...,Herstellung von Speisen und Produktion in der ...,Abgeschlossene Berufsausbildung als Koch/Köchi...,Selbstständiges Arbeiten in einem kreativen un...,27,9,2022

In [5]:
execute(f'''
SELECT *
  FROM curated.job_location
 ORDER BY load_timestamp DESC,
          job_id DESC
 LIMIT 20
''')

     job_id      load_timestamp           location day month  year
0   8756987 2022-09-27 22:00:00             Munich  27     9  2022
1   8756986 2022-09-27 22:00:00            München  27     9  2022
2   8756985 2022-09-27 22:00:00           Nürnberg  27     9  2022
3   8756984 2022-09-27 22:00:00  Frankfurt am Main  27     9  2022
4   8756983 2022-09-27 22:00:00             Berlin  27     9  2022
5   8756982 2022-09-27 22:00:00           Konstanz  27     9  2022
6   8756981 2022-09-27 22:00:00            Leipzig  27     9  2022
7   8756980 2022-09-27 22:00:00         Düsseldorf  27     9  2022
8   8756979 2022-09-27 22:00:00                Ulm  27     9  2022
9   8756978 2022-09-27 22:00:00  Frankfurt am Main  27     9  2022
10  8756977 2022-09-27 22:00:00  Frankfurt am Main  27     9  2022
11  8756976 2022-09-27 22:00:00           Konstanz  27     9  2022
12  8756975 2022-09-27 22:00:00         Ingolstadt  27     9  2022
13  8756974 2022-09-27 22:00:00         Ingolstadt  27     9  2022
14  8756973 2022-09-27 22:00:00               Kiel  27     9  2022
15  8756972 2022-09-27 22:00:00              Neuss  27     9  2022
16  8756971 2022-09-27 22:00:00           Hannover  27     9  2022
17  8756970 2022-09-27 22:00:00           Hannover  27     9  2022
18  8756969 2022-09-27 22:00:00               Köln  27     9  2022
19  8756968 2022-09-27 22:00:00             Berlin  27     9  2022